if(NOT Blaze_FOUND)
  if(JSONBINPACK_INSTALL)
    set(SOURCEMETA_BLAZE_INSTALL ON CACHE BOOL "enable installation")
  else()
    set(SOURCEMETA_BLAZE_INSTALL OFF CACHE BOOL "disable installation")
  endif()

  set(BLAZE_TEST OFF CACHE BOOL "disable")
  set(BLAZE_CONFIGURATION OFF CACHE BOOL "disable")
  set(BLAZE_CONTRIB OFF CACHE BOOL "disable")
  add_subdirectory("${PROJECT_SOURCE_DIR}/vendor/blaze")
  include(Sourcemeta)
  set(Blaze_FOUND ON)
endif()
