find_program(SHELLCHECK_BIN NAMES shellcheck)

if(SHELLCHECK_BIN)
  add_custom_target(shellcheck
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    VERBATIM
    COMMAND "${SHELLCHECK_BIN}" ${JSONBINPACK_SH_SOURCE_FILES})
endif()
