name: JSON BinPack
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies (macOS)
        if: runner.os == 'macos'
        run: |
          brew install cmake clang-format shellcheck
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - uses: actions/checkout@v2
      - run: shellcheck scripts/*.sh
      - run: cmake --version
      - run: cmake --preset release --log-context
      - run: cmake --build --preset release --target clang_format_test
      - run: cmake --build --preset release
      # TODO: Re-enable clang-tidy
      # - run: cmake --build --preset release --target clang_tidy
      - run: ctest --preset release

  website:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make html
      # Only deploy website from the master branch
      - if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/www
