name: JSON BinPack

# Do not run this job for changes that only affect the website
on:
  push:
    paths-ignore:
      - 'www/**'

# Do not run multiple jobs for the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Only run clang-tidy on GNU/Linux as a separate jobs
  # given how expensive clang-tidy this, even more on
  # other platforms.
  # clang-tidy:
    # runs-on: ubuntu-20.04
    # if: github.ref != 'refs/heads/master'
    # steps:
      # - uses: actions/checkout@v2
      # - run: sudo apt-get install --yes clang-tidy
      # - run: cmake --version
      # - run: cmake --preset release --log-context
      # - run: cmake --build --preset release --target clang_tidy

  test:
    strategy:
      matrix:
        platform:
          - os: macos-11
            cc: clang
            cxx: clang++
          # - os: ubuntu-20.04
            # cc: gcc
            # cxx: g++

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - name: Install dependencies (macOS)
        if: runner.os == 'macos'
        run: brew install cmake clang-format shellcheck
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - name: Install dependencies (GNU/Linux)
        if: runner.os == 'linux'
        run: sudo apt-get install --yes clang-format shellcheck

      - uses: actions/checkout@v2
      - run: shellcheck scripts/*.sh
      - run: cmake --version
      - run: cmake --preset release --log-context
      - run: cmake --build --preset release --target shellcheck
      - run: cmake --build --preset release --target clang_format_test
      - run: cmake --build --preset release
      - run: ctest --preset release
