name: JSON BinPack
on:
  - push
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install --yes clang-tidy clang-format
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: cmake --preset release --log-context
      - run: cmake --build --preset release --target clang_format_test
      - run: cmake --build --preset release --target clang_tidy
      - run: cmake --build --preset release
      - run: ctest --preset release
      - run: make html

      # Only deploy website from the master branch
      - if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/www
