name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt-get install --yes doxygen sassc
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONBINPACK_CLI:BOOL=OFF
          -DJSONBINPACK_NUMERIC:BOOL=OFF
          -DJSONBINPACK_RUNTIME:BOOL=OFF
          -DJSONBINPACK_COMPILER:BOOL=OFF
          -DJSONBINPACK_TESTS:BOOL=OFF
          -DJSONBINPACK_WEBSITE:BOOL=ON
          -DJSONBINPACK_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target website
      - run: cmake --build ./build --config Release --target doxygen
