name: JSON BinPack
on:
  - push

jobs:
  website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install --yes doxygen doxygen-latex bundler
      - run: cmake --version
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONBINPACK_CLI:BOOL=OFF
          -DJSONBINPACK_TESTS:BOOL=OFF
      - run: cmake --build ./build --config Release --target bundler
      # Jekyll is often flaky on GitHub Actions
      - run: ./scripts/retry.sh cmake --build ./build --config Release --target jekyll
      - run: cmake --build ./build --config Release --target doxygen
      # Only deploy website from the main branch
      - if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/release/www
