name: website
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: website-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt-get install --yes doxygen doxygen-latex bundler
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONBINPACK_CLI:BOOL=OFF
          -DJSONBINPACK_RUNTIME:BOOL=ON
          -DJSONBINPACK_COMPILER:BOOL=ON
          -DJSONBINPACK_TESTS:BOOL=OFF
          -DJSONBINPACK_WEBSITE:BOOL=ON

      # Jekyll is often flaky on GitHub Actions
      - run: ./scripts/retry.sh cmake --build ./build --config Release --target jekyll
      - run: cmake --build ./build --config Release --target doxygen

      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/release/www
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
