name: website
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt-get install --yes doxygen doxygen-latex bundler
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONBINPACK_CLI:BOOL=OFF
          -DJSONBINPACK_RUNTIME:BOOL=ON
          -DJSONBINPACK_COMPILER:BOOL=ON
          -DJSONBINPACK_TESTS:BOOL=OFF
          -DJSONBINPACK_WEBSITE:BOOL=ON
      # Jekyll is often flaky on GitHub Actions
      - run: ./scripts/retry.sh cmake --build ./build --config Release --target jekyll
      - run: cmake --build ./build --config Release --target doxygen
